FEE_CONSTANTS_URL = "https://raw.githubusercontent.com/balancer/multisig-ops/main/config/protocol_fees_constants.json"
ALLIANCE_CONFIG_URL = "https://raw.githubusercontent.com/balancer/multisig-ops/main/config/alliance_fee_share.json"
PARTNER_CONFIG_URL = "https://raw.githubusercontent.com/balancer/multisig-ops/main/config/partner_fee_share.json"
POOL_OVERRIDES_URL = "https://raw.githubusercontent.com/balancer/multisig-ops/main/config/pool_incentives_overrides.json"
VOTEMARKET_CONFIG_URL = "https://raw.githubusercontent.com/stake-dao/contracts-monorepo/main/packages/votemarket/data/votemarkets.json"
SNAPSHOT_URL = "https://hub.snapshot.org/graphql?"
HH_API_URL = "https://api.hiddenhand.finance/proposal"
GAUGE_MAPPING_URL = "https://raw.githubusercontent.com/aurafinance/aura-contracts/main/tasks/snapshot/gauge_choices.json"
