name: Trigger Fee Collection on Mimic Merge

on:
  workflow_dispatch:
    inputs:
      manual_date:
        description: "End date to process (YYYYMMDD format)"
        required: true
        type: string
  push:
    branches:
      - test-workflow
    paths:
      - "fee_allocator/fees_collected/*.json"

jobs:
  process_fees:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get date from filename
        id: get-date
        run: |
          if [ ! -z "${{ inputs.manual_date }}" ]; then
            echo "end-date=${{ inputs.manual_date }}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get the path of the changed JSON file
          JSON_PATH=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'fee_allocator/fees_collected/.*\.json$' | head -n 1)

          if [ -z "$JSON_PATH" ]; then
            echo "No JSON file found in recent changes."
            exit 1
          fi

          echo "JSON Path: $JSON_PATH"

          # Extract the end date from filename using cut
          END_DATE=$(basename "$JSON_PATH" | cut -d'_' -f5 | cut -d'.' -f1)

          echo "end-date=$END_DATE" >> $GITHUB_OUTPUT

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Collect fees
        env:
          DRPC_KEY: ${{ secrets.DRPC_KEY }}
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
        run: |
          pwd
          end_day=${{ steps.get-date.outputs.end-date }}
          start_day=$(date -d "$end_day -14 days" +%Y-%m-%d)
          date_range_string="${start_day}_${end_day}"
          echo $date_range_string
          start_timestamp=$(date -d "$start_day 00:00:00" +"%s")
          end_timestamp=$((start_timestamp + 60*60*24*14)) # 2 weeks later
          pip3 install -r requirements.txt

          # v2 run
          python3 main.py --ts_now $end_timestamp --ts_in_the_past $start_timestamp --fees_file_name v2_fees_${date_range_string}.json --output_file_name v2_incentives_${date_range_string}.csv --protocol_version v2
          # v3 run
          python3 main.py --ts_now $end_timestamp --ts_in_the_past $start_timestamp --fees_file_name v3_fees_${date_range_string}.json --output_file_name v3_incentives_${date_range_string}.csv --protocol_version v3
          # merge v2/v3 payload
          python3 combine_payloads.py --payload_file_name v2_fees_${date_range_string}.json

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "task: new fees report ending ${{ steps.get-date.outputs.end-date }}"
          title: "Biweekly Fee Report ending ${{ steps.get-date.outputs.end-date }}"
          body: |
            Checks before merging:
            - [ ] all pools must be a core pool
            - [ ] `total_incentives` + `fees_to_vebal` + `fees_to_dao` == [usdc onchain](https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48?a=0x7c68c42de679ffb0f16216154c996c354cf1161b)
            - [ ] `aura_incentives` / `total_incentives` ~= aurabal's vebal capture (https://app.aura.finance/#/stats)
            - [ ] `earned_fees` <= total_swept onchain (per chain)
            - [ ] `fees_to_dao` / (`fees_to_vebal` + `fees_to_dao` + `total_incentives`) == .175
            - [ ] `min(aura_incentives)` > threshold
            - [ ] `min(bal_incentives)` > threshold
            - [ ] latest [vote round data added](https://github.com/aurafinance/aura-contracts/pulls?q=is%3Apr+is%3Aclosed) by aura team?

            Additional checks:
            - [ ] paladin quest v2 claimable earnings > $10k? https://quest.paladin.vote/#/claim
          branch: gha-biweekly-fees
          branch-suffix: timestamp
          delete-branch: true
          labels: "Biweekly-Report"
