name: Update Core Pool Earned Fees

on:
  workflow_dispatch:
  schedule:
    # every 12 hours
    - cron: "0 0,12 * * *"

jobs:
  generate_earned_fees:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: "collect-fees-cron"

      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate earned fees CSVs
        env:
          DRPC_KEY: ${{ secrets.DRPC_KEY }}
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          pwd
          python generate_earned_fees.py

      - name: Commit CSV files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: "collect-fees-cron"
          file_pattern: "fee_allocator/allocations/incentives/current_fees/*_earned_fees_*.csv"
          commit_message: "ci: update core pool earned fees CSVs"